#!/bin/bash
source "$CONFIG_DIR/colors.sh"
PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

sketchybar --bar position=top sticky=on y_offset=10 height=40 corner_radius=10 topmost=off blur_radius=30 padding_right=10 padding_left=10 margin=10 color=$BAR_COLOR

sketchybar --default icon.font="SF Pro:Semibold:15.0" \
  icon.color=$WHITE \
  label.font="JetBrains Mono:Semibold:15.0" \
  label.color=$WHITE \
  background.color=$ITEM_BG_COLOR \
  background.corner_radius=5 \
  background.height=24 \
  padding_left=5 \
  padding_right=5 \
  label.padding_left=4 \
  label.padding_right=10 \
  icon.padding_left=10 \
  icon.padding_right=4

sketchybar --default "${default[@]}"

sketchybar --add event aerospace_workspace_change
sketchybar --add event aerospace_mode_change
sketchybar --add event display_volume_change

source $ITEM_DIR/calendar.sh
source $ITEM_DIR/cpu.sh

source $ITEM_DIR/ONE_THING.sh

source $ITEM_DIR/apple.sh
source $ITEM_DIR/aerospace.sh
source $ITEM_DIR/front_app.sh

sketchybar --update
